### ISSUE TITLE
Scope note: fakeRepository missing ClearBoardOwner breaks bazel build //leaflab/api:api_test

### ISSUE THREAD

**Issue by QMasterMoo** [whale-net/everything#1806]
Part of #1756
from:worker

## What's broken

`leaflab/api/server_test.go`'s `fakeRepository` does not implement `ClearBoardOwner`, one of the five methods `repositoryStore` requires per FR11-FR14 (admin ownership screen). `bazel build //leaflab/api:api_test` (and therefore `bazel build //leaflab/...`) fails at HEAD (`7b8f3202`, base of this plan's dependency chain) with:

```
leaflab/api/server_test.go:327:29: cannot use repo (variable of type *fakeRepository) as repositoryStore value in argument to NewLeafLabAPIServer: *fakeRepository does not implement repositoryStore (missing method ClearBoardOwner)
```

Confirmed pre-existing (not introduced by #1772's work): reproduces identically via `git stash` back to the unmodified worktree tip before any #1772 changes. Introduced by commit `6a9205fc` ("wire admin ownership screen RPCs -- list, reassign, clear"), part of this same root plan's history but a different task than #1772 (FR9/NFR4 processor convergence).

## Impact

Blocks `bazel build //leaflab/...` and `bazel test //leaflab/api:api_test` entirely -- every other target in `//leaflab/...` builds cleanly (verified via `bazel build -- //leaflab/... -//leaflab/api:api_test`).

## Suggested fix

Add a `ClearBoardOwner(ctx context.Context, boardID int64) error` method to `fakeRepository` in `leaflab/api/server_test.go`, in the same style as its existing `ReassignBoardOwner`/`ListOwnedBoards` fakes -- likely a one-line addition tracking cleared boards the way `renamedSensors`/`claimedBoards` already do for their own RPCs.
